### ISSUE TITLE
Make uri_encode faster

### ISSUE THREAD

**Issue by smls** [dnmfarrell/URI-Encode#4]
`uri_encode` is quite slow right now for small strings, which is I think a common thing to do (e.g. encoding each URL query fragment individually when building up a HTTP GET query string).

Replacing this:

    .trans(@escape_chars => @escape_encoding);

with this:

    .subst(/<[\x00..\xff]-[a..zA..Z0..9_.~-]>/, *.ord.fmt('%%%02X'), :g)

seems to make it much faster (and wouldn't even need the pre-compiled data structures). I haven't properly benchmarked it yet nor investigated further optimization possibilities though.

**Comment by dnmfarrell** [comment]
Interesting ... thanks for this. Transcoding should be faster than a regex, weird!

**Comment by smls** [comment]
I would guess it's probably because the regex only has to be compiled (and optimized) once, at program compile time - whereas `tr` needs to do argument handling and initialization work on every call.

Also, I imagine that a regex can avoid expanding a range like `a..z` into a big alternation, and instead simply check `ord(a) <= ord($current_character) <= ord(z)`.

But that's just guesswork. The pro's on #perl6 will know more.

**Comment by dnmfarrell** [comment]
Finally got around to testing and updating this. It's ALOT faster, thank you!
