### ISSUE TITLE
url_encode too enthusiastic

### ISSUE THREAD

**Issue by jonathanstowe** [dnmfarrell/URI-Encode#6]
Hi,
when you ignore reserved chars you are not ignoring the complete list as per https://tools.ietf.org/html/rfc3986#section-2.2 which means that things that are specified refering to that version of the URI spec may not work as documented :)  Specifically I am using test data for https://github.com/jonathanstowe/URI-Template which is generated directly from the spec and  some are failing currently because of this.

When I've got a bit further with what I'm doing I'll look at making a PR for this.

Thanks.

**Comment by dnmfarrell** [comment]
You're right, thanks for picking up on this. My naiive implementation is wrong. Looking into it ...
